name: Check_python_version

on: [push]

jobs:
  build:

    runs-on: ${{matrix.os}}
    steps: 
        - name: Upgrade pip
          run: |
            pip install pip --upgrade
            pip install wheel
        - name: Check python version
          run: |
              python -v
    strategy:
      matrix:
        os: [ubuntu-latest]
        python version: ["3.11"]
        
